---
- name: Backup MikroTik configuration
  hosts: mikrotik
  gather_facts: no
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: community.routeros.routeros
    ansible_become: no
    backup_dir: "{{ playbook_dir }}/backups"
  tasks:
    - name: Get export configuration
      community.routeros.command:
        commands:
          - /export
      register: config_output

    - name: Save config to file
      delegate_to: localhost
      copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}.rsc"
