# 00_container_mode.yml
---
- name: Enable container mode
  hosts: mikrotik
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: community.routeros.routeros
    ansible_command_timeout: 60
    usb_path: "usb1"

  tasks:
    - name: Configure container registry and tmpdir
      community.routeros.command:
        commands:
          - /container/config/set registry-url=https://registry-1.docker.io tmpdir={{ usb_path }}/docker/pull
      ignore_errors: yes

    - name: "!!! ВНИМАНИЕ !!!"
      fail:
        msg: "СЕЙЧАС БУДЕТ КОМАНДА device-mode - ПРИГОТОВЬСЯ ВЫДЕРНУТЬ ПИТАНИЕ (5 минут)"
      ignore_errors: yes

    - name: "ВЫДЕРГИВАЙ ПИТАНИЕ СЕЙЧАС"
      community.routeros.command:
        commands:
          - /system/device-mode/update container=yes
      ignore_errors: yes

    - name: Готово
      debug:
        msg: "Если выдернул питание вовремя - container yes"