---
- name: "01: Network"
  hosts: mikrotik
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: community.routeros.routeros
    ansible_connection: ansible.netcommon.network_cli
  vars_files:
    - vars.yml
  
  tasks:
    - name: Проверить существование veth
      community.routeros.command:
        commands:
          - /interface veth print count-only where name={{ container_name }}
      register: veth_exists

    - name: Создать veth интерфейс
      community.routeros.command:
        commands:
          - /interface veth add name={{ container_name }} address={{ container_ip }}/24 gateway={{ container_gateway }}
      when: veth_exists.stdout[0] | int == 0

    - name: Проверить существование bridge port
      community.routeros.command:
        commands:
          - /interface bridge port print count-only where interface={{ container_name }}
      register: port_exists

    - name: Добавить veth в bridge
      community.routeros.command:
        commands:
          - /interface bridge port add bridge={{ docker_bridge }} interface={{ container_name }}
      when: port_exists.stdout[0] | int == 0

    - name: Результат
      ansible.builtin.debug:
        msg: "Veth {{ container_name }} IP {{ container_ip }}"
