# mihomo_all.yml
---
- name: "01b: Network (Bridge + NAT + DNS)"
  ansible.builtin.import_playbook: 01b_network.yml

- name: "02: SMB mount"
  ansible.builtin.import_playbook: 02_smb_mount.yml

- name: "03: Configs"
  ansible.builtin.import_playbook: 03_configs.yml

- name: "04: Container"
  ansible.builtin.import_playbook: 04_container.yml