# mikrotik/mihomo/test_connection.yml
---
- name: Test connection
  hosts: mikrotik
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: community.routeros.routeros

  tasks:
    - name: Test device-mode command
      community.routeros.command:
        commands:
          - /system/device-mode/print
      register: result

    - debug:
        msg: "{{ result.stdout_lines }}"