# group_vars/all.yml
---
zabbix_version: "7.0"
db_name: zabbix
db_user: zabbix
db_password: "zabbix_secure_pass_123"

# Telegram alerts
tg_token: "5618230805:AAFAIcZme9nBm_TUPnmhgdG3_gTT3eLP1Bs"
tg_chat_id: "1009377001"
